import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Aside from "./components/aside/aside";
import Footer from "./components/footer/footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen flex overflow-hidden"></body>
      <Aside />
      <main className="flex-1 flex flex-col overflow-y-auto bg-white">
        <div className="flex-1 w-full">

          {children}
        </div>
        <Footer />
      </main>
    </html>
  );
}
